version: "3"
services:
  postgres:
    image: "postgres:11.7-alpine"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=library
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
